### PR TITLE
Support older stack versions (Version 1.1.0 x86_64 hpack-0.13.0) and stack.yaml for easy local compile

### PR DESCRIPTION
**Pull request by ruslantalpa**
Let me know if there are things you like changed
For example i am not sure  tests/test-package/test-package.cabal is needed anymore

### CODE REVIEW

**Comment by ruslantalpa** [comment]
Unrelated to this PR.
after this fix, the old stack worked and also the new one does, but i am still seeing some errors like these, any pointers to how to fix this? If this is a know problem with stack projects, if you give me some pointers as to what basically is going on and where in the code to look for fixing this, i would spend a few days and see if i can fix this
```
Sublime Haskell: drop prepared completions
Sublime Haskell: hsdev types returns error: ghc error, msg: Failed to load interface for ‘Control.Lens’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Data.Ranged.Ranges’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Data.Text’
Perhaps you meant Data.Set (from containers-0.5.7.1)
Use -v to see a list of the files searched for.
Failed to load interface for ‘Hasql.Pool’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Hasql.Transaction’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Text.Parsec.Error’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Text.ParserCombinators.Parsec’
Perhaps you meant
  Text.ParserCombinators.ReadPrec (from base-4.9.0.0)
  Text.ParserCombinators.ReadP (from base-4.9.0.0)
Use -v to see a list of the files searched for.
Failed to load interface for ‘Text.InterpolatedString.Perl6’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Network.HTTP.Types.Header’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Network.HTTP.Types.Status’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Network.HTTP.Types.URI’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Network.Wai’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Network.Wai.Middleware.RequestLogger’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Web.JWT’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Data.Aeson’
Perhaps you meant Data.Version (from base-4.9.0.0)
Use -v to see a list of the files searched for.
Failed to load interface for ‘Data.Aeson.Types’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Data.Aeson.Lens’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Data.Vector’
Perhaps you meant Data.Functor (from base-4.9.0.0)
Use -v to see a list of the files searched for.
Failed to load interface for ‘Hasql.Transaction’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Data.HashMap.Strict’
Perhaps you meant
  Data.IntMap.Strict (from containers-0.5.7.1)
  Data.Map.Strict (from containers-0.5.7.1)
Use -v to see a list of the files searched for.
attempting to use module ‘PostgREST.ApiRequest’ (src/PostgREST/ApiRequest.hs) which is not loaded
attempting to use module ‘PostgREST.Auth’ (src/PostgREST/Auth.hs) which is not loaded
attempting to use module ‘PostgREST.Config’ (src/PostgREST/Config.hs) which is not loaded
attempting to use module ‘PostgREST.DbStructure’ (src/PostgREST/DbStructure.hs) which is not loaded
attempting to use module ‘PostgREST.Error’ (src/PostgREST/Error.hs) which is not loaded
attempting to use module ‘PostgREST.Parsers’ (src/PostgREST/Parsers.hs) which is not loaded
attempting to use module ‘PostgREST.RangeQuery’ (src/PostgREST/RangeQuery.hs) which is not loaded
attempting to use module ‘PostgREST.Middleware’ (src/PostgREST/Middleware.hs) which is not loaded
attempting to use module ‘PostgREST.QueryBuilder’ (src/PostgREST/QueryBuilder.hs) which is not loaded
attempting to use module ‘PostgREST.Types’ (src/PostgREST/Types.hs) which is not loaded
attempting to use module ‘PostgREST.OpenAPI’ (src/PostgREST/OpenAPI.hs) which is not loaded
Failed to load interface for ‘Web.Cookie’
Use -v to see a list of the files searched for.
Failed to load interface for ‘Protolude’
Use -v to see a list of the files searched for.
, id: 84
```

**Comment by mvoidex** [comment]
This is known bug I mentioned before

**Comment by ruslantalpa** [comment]
Is there any issue that tracks progress on this. I would like to look into it (i'll also fix the failing tests a bit later)

**Comment by mvoidex** [comment]
I've reordered args for stack, so I'll close this. If i missed smth, feel free to reopen or make an issue.

**Pull request closed without merging**
